### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED with node version v.18.9.0

### ISSUE THREAD

**Issue by tomsbox** [Kitware/glance#477]
Hello,

when I try "npm run dev" and I get this error:

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\Appl\webapps\glance\node_modules\webpack\lib\util\createHash.js:155:18)
    at BulkUpdateDecorator.digest (C:\Appl\webapps\glance\node_modules\webpack\lib\util\createHash.js:80:21)
    at C:\Appl\webapps\glance\node_modules\webpack\lib\DefinePlugin.js:595:38
    at _next28 (eval at create (C:\Appl\webapps\glance\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:40:1)
    at _next6 (eval at create (C:\Appl\webapps\glance\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (C:\Appl\webapps\glance\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:113:1)      
    at Hook.CALL_DELEGATE [as _call] (C:\Appl\webapps\glance\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Appl\webapps\glance\node_modules\webpack\lib\Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Is this a known problem and can anyone help me?

Thanks and greetings, 

Thomas

**Comment by floryst** [comment]
Try using node v16. That can potentially occur with node v17+.

**Comment by jourdain** [comment]
export NODE_OPTIONS=--openssl-legacy-provider
